### ISSUE TITLE
home screen error

### ISSUE THREAD

**Issue by elnosh** [MostroP2P/mostro-web#13]
getting the following error during startup

```
[plugin:vite:import-analysis] Failed to resolve import "~/constants/version" from "layouts/default.vue". Does the file exist?

/home/elnosh/Documents/mostro/mostro-web/layouts/default.vue:72:29

19 |  import { useDisplay } from 'vuetify'
20 |  import { useAuth } from '@/stores/auth'
21 |  import { GIT_COMMIT } from '~/constants/version'
   |                              ^
22 |  import useEllipsis from '~/composables/useEllipsis'
23 |  import pkg from '~/package.json'
```

looks like it is just to display the commit. I commented out that `GIT_COMMIT` to be able to run it locally but not sure what to put in that `/constants` directory

**Comment by bilthon** [comment]
You must run `npm run build` to generate the `constants/version.js` file.

This was not clear in the documentation, I'm amending it [here](https://github.com/MostroP2P/mostro-web/tree/develop?tab=readme-ov-file#build-setup).

Thanks for bringing it up!
