### ISSUE TITLE
the date does not appear correctly

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro-web#14]
When I go to my trades and select the one I am doing, 2 intermediate events appear with the date of just now but that is not correct
![photo_2024-01-31_16-16-20](https://github.com/MostroP2P/mostro-web/assets/140891948/fe22672b-7ee3-4914-85e5-a60bc23a8c30)

**Comment by bilthon** [comment]
This should be now fixed in `v0.0.18`, so I'm closing the issue now. Let me know if there is a regression. Thanks!
