### ISSUE TITLE
Error creating a new order

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro-web#24]
I disabled getalby extension and logged a user with a nsec, then when I try to create a new order I'm having this message in console asking for nip07 extension  

![image](https://github.com/MostroP2P/mostro-web/assets/228364/583eede4-74d3-48ad-b484-862d6a59ee7e)

**Comment by bilthon** [comment]
Fixed in cd885baa118198fa907a0d6b0d67027f7d86e5eb
