### ISSUE TITLE
Reporte: Desaparición de orden de venta publicada.

### ISSUE THREAD

**Issue by villalobosij** [MostroP2P/mostro-web#29]
Publiqué dos órdenes:

Comprando sats por 50 VES c3af710a-5c7b-4e72-8905-dffcce6d69f2 y
Vendiendo sats por 50 VES 0290e15f-89b3-4c60-a361-d66729ed3c85

La orden de venta aparecía en MostroP2P luego desapareció y no la he cancelado ni he recibido notificación de que ha tomada, ahora apreció de nuevo.

Puedo pensar que fué tomada y que se espero que venciera el tiempo para agregar la factura lightning o puede ser un fallo, la verdad no lo sé, perdón por los inconvenientes causados.

**Comment by bilthon** [comment]
Este commit 3b15ec90dbeafc950e213e1beef9312a523d8fd5 debería solucionar este problema
