### ISSUE TITLE
Hold invoice QR code can't be scanned

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro-web#30]
I tried to scan a QR code to sell Bitcoin, the QR code looked like this

![photo_2024-04-03_12-43-49](https://github.com/MostroP2P/mostro-web/assets/228364/c9273747-9f70-4785-8d18-2bb708d141a4)

My mobile couldn't scan this QR code because there is no border on this QR code, to proof this I edited the image and added a white border and then I could scan the invoice, it looked like this

![photo_2024-04-11_16-57-55](https://github.com/MostroP2P/mostro-web/assets/228364/3aff1051-e115-4ed8-bb67-ecf705a0947a)

Please add a white border to the QR code to be scanned correctly

**Comment by pavangadagi** [comment]
@grunch I would like to take this up

**Comment by grunch** [comment]
> @grunch I would like to take this up

great @pavangadagi go ahead

**Comment by bilthon** [comment]
It was actually fixed here 3ab4b16cd4709b140f67f13b8d913f0669116328. This is going to be included in the next release. Sorry I should have closed this earlier.
