### ISSUE TITLE
Rate a user several times (or so it seems)

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro-web#32]
When I rate a user at the end of an operation I can move the cursor over the stars again, select a different number of stars and give the rating again, and so on many times.

Maybe only qualifys the first time but it doesn't show any message that you've already qualified, and it also lets me do it again as many times as I want

**Comment by bilthon** [comment]
Rating is not implemented yet 😁, this is why you observer this behavior. The widget is not actually doing anything as of right now. I'm working on this for the next release though so stay tuned.

**Comment by bilthon** [comment]
Feature introduced here ca68ebdf8d1a896ecb34585044cabd737f8ad265
