### ISSUE TITLE
Show the limit of sats that can be exchanged

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro-web#43]
Some users report that their orders are not created, and that is a bad UX that makes many not try to use Mostro again. Most of the time it happens because they try to create an order outside the range allowed by Mostro, because they do not know the allowed limits.

I suggest putting up some kind of notice showing what the current limits are to avoid these kinds of issues.

**Comment by bilthon** [comment]
This is indeed a good suggestion.

**Comment by bilthon** [comment]
A small message was added in the order creation dialog with a hard-coded amount (for now). If the user were to miss that and proceed with an order above the maximum amount an alert will show up.
