### ISSUE TITLE
When canceling range orders they do not disappear from the market

### ISSUE THREAD

**Issue by Catrya** [MostroP2P/mostro-web#44]
When trying to cancel an order that has a range, it is not removed from the market (but the client does send the message with `action cancel` to Mostro, and event 38383 is published with the order in `status canceled`)

However, pressing the cancel order button does not remove the order from the market, and neither does it close the pop-up window with the order information

This only happened to the user who created the order, for the other users the offer is removed from the market.

This bug only occurs to me with range orders, I have not been able to replicate it with those without ranges.

**Comment by bilthon** [comment]
Fixed in a9c480bb8b05ece32b82cc239975d46c9038c0a8
