### ISSUE TITLE
Maker buy free market

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro-web#5]
* Comprador crea una orden
* Vendedor tomó la orden
* No le aparece al vendedor una notificación que alguien ha tomado su orden (ToDo)
* Vendedor ve la orden tomada en `My orders`, la abre pero no le muestra la hold invoice para pagarla

![image](https://github.com/MostroP2P/mostro-web/assets/228364/19b082d1-fa99-4b26-b038-d2bf24f9a5bb)

**Comment by bilthon** [comment]
Fixed [here](https://github.com/MostroP2P/mostro-web/commit/cad684d8c6f613f78d5078f67ced3651e3886449) as well. The notification system is something that's pending and was just added as an independent issue.
