### ISSUE TITLE
Trying to use BRL

### ISSUE THREAD

**Issue by Gkasgd** [MostroP2P/mostro-web#50]
When I try to post a SELL order with a range of various amounts, example: 10-100 BRL, it fails to create and throw this error :

"The order you just attempted to create has an amount that is too large. Please try again with a smaller amount."

It happend with USD too.
![image](https://github.com/user-attachments/assets/1a4e4f2c-0fb3-482e-9344-a7f8c030e92f)

Edit: It happened on web version, several times.

**Comment by bilthon** [comment]
Yes, this happens because the upper limit of your fiat range, 100 BRL would be ~31K sats, which is higher than our current maximum allowed limit of 20K sats.
