### ISSUE TITLE
Seller take own order

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro-web#7]
* Seller creates an order
* Seller takes the order
* Mostro send a message with action `CantDo` but I get this screen
![image](https://github.com/MostroP2P/mostro-web/assets/228364/2d770daf-9759-4d69-81ea-e17e7a261a0a)

Instead it shoud let know to the user that can't take its own order

**Comment by bilthon** [comment]
This has been fixed, the creator cannot take his own orders anymore.
