### ISSUE TITLE
Reviewing order flow

### ISSUE THREAD

**Issue by grunch** [MostroP2P/mostro-web#8]
branch: `develop`

Testing case: seller and buyer add their own nsec1 to their own respective web browser session

Seller creates an order
Buyer took the order, the order message is duplicated
![Captura desde 2023-06-27 13-11-36](https://github.com/MostroP2P/mostro-web/assets/228364/f521b5a3-fa32-48d0-8f4d-fdcdcb4e1626)

Buyer send the invoice and shows again a duplicated message
![Captura desde 2023-06-27 13-12-06](https://github.com/MostroP2P/mostro-web/assets/228364/91b34005-9fda-418f-bd07-ba5f18fa53ad)

Seller receives a notification, but it's not the first one but the last one, this is confusing, the more recent notification must be the first one the user can see
![Captura desde 2023-06-27 13-12-46](https://github.com/MostroP2P/mostro-web/assets/228364/4c4d0873-4f62-4c13-a3e6-9373d770f8c1)

When the seller click on the buyer pubkey it shows a chat but after the seller writes nothing happens, and also we have duplicated messages here too
![Screenshot 2023-06-27 at 13-13-27 mostro-web-ui - mostro-web-ui](https://github.com/MostroP2P/mostro-web/assets/228364/b3fabd7d-f658-4fd5-a8a8-0556ecadf02b)

The buyer only can see a `dispute` button but not a `fiatsent` button and can't continue, also duplicated message here too.
![Captura desde 2023-06-27 13-16-20](https://github.com/MostroP2P/mostro-web/assets/228364/bd44fa20-ad7d-485f-96c2-91b6c5bc2159)

**Comment by bilthon** [comment]
Several issues here! but they should be all fixed in the last commit.
